# Generated by Django 5.2.10 on 2026-02-16 17:43

from django.db import migrations


def populate_pet_model(apps, schema_editor):
    PetModel = apps.get_model('pets', 'Pet')
    PetModel.objects.create(
        name='Buddy',
        date_of_birth='2018-05-20',
        personal_photo='https://example.com/photos/buddy.jpg',
    )


def reverse_populate_pet_model(apps, schema_editor):
    PetModel = apps.get_model('pets', 'Pet')
    PetModel.objects.filter(name='Buddy').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=populate_pet_model, reverse_code=reverse_populate_pet_model),
    ]
